name: build_jsons
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-jsons:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create JSON of each CSV /passes and subdirectories
        run: |
          find passes -name "*.csv" -print0 | while IFS= read -r -d '' file; do
            echo "Processing: $file"
            cat $file | python -c 'import csv, json, sys; print(json.dumps([dict(r) for r in csv.DictReader(sys.stdin)]))' > temp.json
            mv temp.json "$file.json"
          done

      - uses: stefanzweifel/git-auto-commit-action@v5



