name: Run automatic CI sequence

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  uppercase_content:
    uses: ./.github/workflows/uppercase_content.yml
    permissions:
      contents: write
      
  build_jsons:
    needs: uppercase_content  # Run action-b after action-a completes
    uses: ./.github/workflows/build_jsons.yml  # Path to your b.yml workflow file
    permissions:
      contents: write

  build_nodes_edges_json:
    needs: build_jsons  # Run action-b after action-a completes
    uses: ./.github/workflows/generate_nodes_edges_json.yml  # Path to your b.yml workflow file
    permissions:
      contents: write
