# This is a basic workflow to help you get started with Actions

name: lowercase_content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lowercase-filename:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: lowercase all csv content
        run: |
          find passes -name "*.csv" -print0 | while IFS= read -r -d '' file; do
            tr '[:upper:]' '[:lower:]' < "$file" > temp.csv
            mv temp.csv "$file"
          done
